language: python
python:
  - "2.6"
  - "2.7"

# install dependencies
before_install:
  - sudo apt-get install python-dev
  - sudo apt-get install libboost-dev
  - sudo apt-get install libboost-python-dev
  - cp -rf Recast\(Patched\)/* Recast/

# build script
install:
  - python setup.py install

# run tests
script:
  - cd examples
  - echo 'no tests'
